# Generated by Django 4.2.7 on 2023-11-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="mobile_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
