# Generated by Django 4.2.7 on 2023-11-16 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_rename_phone_number_user_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must be a valid phone number",
                        regex="^\\d{10,15}$",
                    )
                ],
            ),
        ),
    ]
