# Generated by Django 4.2.7 on 2023-11-16 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_remove_user_mobile_number_user_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="mobile_number",
        ),
    ]
